name = "nci-eras-pages"
compatibility_date = "2026-09-11"
main = "src/index.js"

[assets]
directory = "./"

[[d1_databases]]
binding = "DB"
database_name = "nci-eras-db"
database_id = "d6308105-02cc-4082-9872-5f0b890305e9"
